---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-%%role_name%%-${%%ROLE_NAME%%_VERSION:-X.X.X}"
    hostname: %role_name%
    image: "${NAMESPACE:-rockylinux}/${IMAGE:-rockylinux}:${TAG:-9-ubi-init}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - name: local
provisioner:
  name: ansible
  env:
    %%ROLE_NAME%%_VERSION: ${%%ROLE_NAME%%_VERSION:-X.X.X}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint